### PR TITLE
IDL changes for setMetadata for 3.2.2 webrtc nv use case

### PR DESCRIPTION
**Pull request by palak8669**
***
<a href="https://pr-preview.s3.amazonaws.com/palak8669/webrtc-encoded-transform/pull/202.html" title="Last updated on Oct 12, 2023, 8:09 AM UTC (0a86a80)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-encoded-transform/202/7721c15...palak8669:0a86a80.html" title="Last updated on Oct 12, 2023, 8:09 AM UTC (0a86a80)">Diff</a>

### CODE REVIEW

**Comment by youennf** [comment]
As discussed during yesterday editor's call, here is some feedback for this issue.

As expressed in https://github.com/w3c/webrtc-encoded-transform/pull/201#issuecomment-1740387694, WebRTC encoded transform is a very specific tool. It does not seem to be the most appropriate tool for 3.2.2 webrtc nv use cases. Given alternative APIs have been proposed for this use case, we should take the time to evaluate them and pick the best one.

Also 3.2.2 use case definition is being refined in https://github.com/w3c/webrtc-nv-use-cases/pull/123, the target seems to be ultra low latency.

For 3.2.2 ultra low latency use case, doing processing at packet level (both for forwarding from first to second link and for processing the second link feedback) would probably be more appropriate, like what SFUs are doing. WebRTC encoded transform is only handling frames, not packets, which is one example of the potential mismatch.
Another mismatch is that WebRTC encoded transform does not deal with packet loss.

When some additional latency is ok, which seems to be the use case behind this PR, using RTCPeerConnection for the first link (limited bandwidth) and data channel for the second link (corporate network) is already feasible and should provide good results. I would be interested in understanding the end user benefits of the proposed new approach with this already feasible implementation strategy.

**Comment by palak8669** [comment]
We want to solve the use case first mentioned in [WebRTC July 2023 meeting – (SetMetadata for redundant relay PCs.)](https://www.w3.org/2023/07/18-webrtc-minutes.html#t10). Though using Data channels for this use case is possible, it adds more latency than RTP would using the proposed encoded transforms approach. In addition to this, using data channels here would require the app to write, tune and maintain its own custom jitter buffer along with defining a system to smoothly render vide from JS, which can be difficult due to timing restrictions.

Though encoded transforms do not allow handling packets, we think the added latency on waiting to assemble packets to a frame is still much less than data channels and something that our use case can handle. 

In regards to the concern about packet loss management, this is being addressed in [Congestion control API proposal](https://github.com/w3c/webrtc-encoded-transform/pull/207)

**Comment by dontcallmedom** [comment]
the CI is still failing because the parameter to `setMetadata()` is a dictionary, so should be optional or have a required field; I suspect the right solution would be to make the `rtpTimestamp` field required (but I'm not entirely sure why this is doing `setMetadata` vs `setRtpTimestamp` since that's the only field that can be updated from what I understand)

**Comment by palak8669** [comment]
The change is for allowing modifications to RTPTimestamp(for audio and video) and frameID and dependencies(for video) as proposed in the [July WG meeting](https://docs.google.com/presentation/d/1ggURAltqkAVZ3tGjh0_RPBnzYbMWd5p-kYUTIiRlrS4/edit#slide=id.g259254aec9f_2_166).

**Comment by alvestrand** [comment]
For use cases where copying the data is not natural (like E2EE encryption), supporting setMetadata seems more natural than the copy constructor.

Constructor language and setMetadata language should be as parallel as possible.

**Comment by guidou** [comment]
Closing in favor of  https://github.com/w3c/webrtc-encoded-transform/pull/223
Will reopen the discussion with a new PR in the future if necessary.

**Pull request closed without merging**
