### PR TITLE
Remove CreateEncodedStream variant API

### PR DESCRIPTION
**Pull request by youennf**
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/webrtc-insertable-streams/pull/64.html" title="Last updated on Apr 15, 2021, 8:07 AM UTC (523b1f1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-encoded-transform/64/1bc1946...youennf:523b1f1.html" title="Last updated on Apr 15, 2021, 8:07 AM UTC (523b1f1)">Diff</a>

### CODE REVIEW

**Comment by youennf** [comment]
Not ready until https://github.com/w3c/webrtc-insertable-streams/pull/62 gets landed

**Comment by alvestrand** [comment]
I do not want to merge this until we have consensus on #18 - the issue is the cases where people actually want main-thread processing.

**Comment by youennf** [comment]
Consensus to go on with this PR was reached at today WebRTC WG interim.

**Comment by guidou** [comment]
What if instead of removing we move it to a "legacy" section, similar to the legacy section in mediacapture-main for the old version of getUserMedia?

**Comment by youennf** [comment]
A legacy section would entail having precise algorithms for the old API on top of the new API. I do not think we want to go there.
I would be more inclined to do like webrtc-stats which has an Obsolete section with the old API WebIDL, no algorithm. Potentially with guidelines on how to transition to the new API.

**Comment by guidou** [comment]
> A legacy section would entail having precise algorithms for the old API on top of the new API. I do not think we want to go there.
> I would be more inclined to do like webrtc-stats which has an Obsolete section with the old API WebIDL, no algorithm. Potentially with guidelines on how to transition to the new API.

I think that would work well.

**Comment by alvestrand** [comment]
Legacy documentation is filed as issue #105.

**Review by alvestrand — APPROVED** [review]

**Comment by foolip** [comment]
@alvestrand is there a Chromium bug to remove the `createEncodedStreams()` methods? They have already shipped in Chrome, so I was surprised when I saw this removed in https://github.com/w3c/webref/commit/f8d3132c5c6457e45b6bcbbafd4c01dc21fbd720.

**Pull request merged**
